# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170711_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='/static_files/assets/media/image/'),
            preserve_default=False,
        ),
    ]
